controller_list:
  - name: fake_owl_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - BJ
      - SJ
      - EJ
      - W1J
      - W2J
      - W3J
  - name: fake_owl_hand_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: owl_arm
    pose: calibrated_pose