
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - BJ 
     - SJ 
     - EJ 
     - W1J 
     - W2J 
     - W3J 
    
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.5
    BJ: {trajectory: 0.1, goal: 0.1}
    SJ: {trajectory: 0.1, goal: 0.1}
    EJ: {trajectory: 0.1, goal: 0.1}
    W1J: {trajectory: 0.1, goal: 0.1}
    W2J: {trajectory: 0.1, goal: 0.1}
    W3J: {trajectory: 0.1, goal: 0.1}

  stop_trajectory_duration: 0.5
  state_publish_rate:  125
  action_monitor_rate: 10

gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - gripper_finger1_joint

  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      finger_joint: {trajectory: 0.1, goal: 0.1}

  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

